/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package football;

public class App {
    

    public static void main(String[] args) {
        Card red = new Card("Ronaldo", 1, "Red", "Man Utd");
        Card yellow = new Card("Maguire", 25, "Yellow", "Man Utd");
        Goal opener = new Goal("Dykes", 40, "QPR");
        Goal finisher = new Goal("Willock", 80, "QPR");
        String[] teams = {"Man Utd", "QPR"};
        String[][] squads ={{"David de Gea","Victor Lindelöf", "Eric Bailly", "Phil Jones", "Harry Maguire", "Lisandro Martínez", "Cristiano Ronaldo", "Bruno Fernandes", "Anthony Martial", "Marcus Rashford", "Mason Greenwood", "Tyrell Malacia", "Christian Eriksen", "Amad Diallo", "Fred", "Raphaël Varane", "Diogo Dalot"},
                            {"Seny Dieng", "Osman Kakay", "Jimmy Dunne", "Rob Dickie", "Jake Clarke-Salter", "Stefan Johansen", "Chris Willock", "Luke Amos", "Lyndon Dykes", "Ilias Chair", "Tyler Roberts", "Jordan Archer", "George Thomas", "Sam Field", "Niko Hämäläinen", "Andre Dozzell", "Macauley Bonne", "Taylor Richards"}};
        Match manUtdVQPR = new Match(1, teams, squads);
        League inMyDreams = new League();
        inMyDreams.addMatch(manUtdVQPR);
        manUtdVQPR.addCard(red);
        manUtdVQPR.addCard(yellow);
        manUtdVQPR.addGoal(opener);
        manUtdVQPR.addGoal(finisher);
        System.out.println(inMyDreams.getResultsForWeek(1));
        System.out.println(inMyDreams.getMatchStats(1, "Man Utd", "QPR"));
    }
}
